version: "3.8"

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: task_management
      DB_USERNAME: root
      DB_PASSWORD: secret

  db:
    image: mysql:8.0
    container_name: task_management
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_management
    volumes:
      - dbdata:/var/lib/mysql
    ports:
    - "3307:3306"

volumes:
  dbdata:
